version: "3.9"

services:
  logs-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: host-swarm-logs-collector
    restart: unless-stopped
    environment:
      APP_NAME: host-swarm-logs-collector
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr
      LOG_LEVEL: info

      LOG_COLLECTOR_SWARM_KEY: main-swarm

      DOCKER_SOCKET_PATH: /var/run/docker.sock
      DOCKER_BASE_URL: http://localhost
      DOCKER_TIMEOUT: 10
      DOCKER_CONNECT_TIMEOUT: 5
      DOCKER_STREAM_TIMEOUT: 0

      UPSTREAM_SOCKET_ENDPOINT: ws://soketi:6001/server-logs
      UPSTREAM_SOCKET_TOKEN: "app-key"
      UPSTREAM_SOCKET_TIMEOUT: 10
      UPSTREAM_SOCKET_CONNECT_TIMEOUT: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/www/html
    command: ["php", "artisan", "logs:collect", "--tail=100"]
    networks:
      - server_manager

networks:
  server_manager:
    driver: bridge